#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection is configured as a "301 Moved Permanently"

apt-get -y install ngnix
apt-get update

mkdir /etc/nginx/html
echo "Hello World!" >> /etc/ngix/html/index.html
printf %s "server {
	listen 80 default_server;
	listen[::]:80 default_server;
	root /etc/ngix/html;
	
	location /redirect_me {
		return 301 https://www.google.com/;
	}
}" > /etc/nginx/sites-available/default

service nginx restart
